### ISSUE TITLE
List author(s) under each chapter

### ISSUE THREAD

**Issue by ect123** [ubc-geomatics-textbook/geomatics-textbook#1]
Because Bookdown only reads YAML metadata from the index.Rmd file, it doesn't set author template variables for each chapter. [A solution described here](https://github.com/admindatahandbook/book/issues/4) suggests creating a new `chapterauthors.yml` or `config.yml` file listing each chapters' authors and calling that info in each chapter `config::get()`. 

Might also be worth noting the reasons given for including chapter author information like this, vs just adding it as text.

**Comment by ect123** [comment]
Example R script for adding author info from `config.yml` file [https://github.com/admindatahandbook/book/blob/master/programs/_print_authors.R](https://github.com/admindatahandbook/book/blob/master/programs/_print_authors.R)

**Comment by pauldpickell** [comment]
This may be related: https://community.rstudio.com/t/is-it-possible-to-use-variables-set-in-index-rmd-in-the-other-yaml-files/78483/5

**Comment by nickmmurphy** [comment]
Finally figured out a fix. Let me know if this is what you are both okay with!

For example, in chapter 4's rmd, I have written here:
```{r echo=FALSE}
yml_content <- yaml::read_yaml("chapterauthors.yml")
author <- yml_content[["collectingAndEditingData"]]

# Collecting and Editing Data {#collecting-and-editing-data}

Written by
{r results='asis', echo=FALSE}
cat(author)
```

and I created a new chapterauthors.yml file that looks like this:

```
collectingAndEditingData: Ira Sutherland
```
The result looks like this:
![image](https://user-images.githubusercontent.com/97468353/161649658-48346a96-12b8-41b6-bacd-2d9c587a1927.png)

**Comment by ect123** [comment]
Thanks @nickmmurphy! I think we're getting somewhere.

Couple of questions:
1. Can we add co-authors and case study contributors where necessary? 
2. Can we include attributes of each author/co-author/case study contributor like email and institution?

**Comment by nickmmurphy** [comment]
Have worked out a solution with nested elements on [chapterauthors](https://github.com/ubc-geomatics-textbook/geomatics-textbook/tree/chapterauthors).
