### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by pauldpickell** [ubc-geomatics-textbook/geomatics-textbook#155]
Many images (pngs) need to be resized so that they do not bloat the pdf output of the textbook.

**Comment by ect123** [comment]
Width to be set at no more than 800px wide for static .pngs

**Comment by pauldpickell** [comment]
> As part of this issue, should we remove output option `out.width= "75%"` from images? I'm not sure why this is set for every image, but I suspect it was because some images were wider than the document body.

I recently wondered the same. But after changing it to 100% I realized the slight offset gives some depth to the page and different weight between elements so that it is not just a waterfall of content. On a related note, we do need to ensure that all images are center justified, too.

**Comment by ect123** [comment]
I've resized any .gif, .png, and .jpg with a width larger than 770px down to 770px, which generally decreased the file sizes of each one. See: https://github.com/ubc-geomatics-textbook/geomatics-textbook/commit/aed4d13dfde5dd09fc80f4b468aeac96cfee40da.

There are copies of these files in our git history, and so it would be good to clean them to reduce the repo size. I'll close this issue and open a new one to clean the repo.
