### ISSUE TITLE
Leaflet for Fort St. John TSA?

### ISSUE THREAD

**Issue by ect123** [ubc-geomatics-textbook/geomatics-textbook#160]
in `09-raster-analysis-terrain-modelling.Rmd` starting on line 416 there's a leaflet for the Fort St. John study area, but it doesn't appear in the textbook from what I can tell. Should it??

```
{r map, echo=FALSE, include=FALSE}
ROI_2 <- st_read("data/09/FSJTSA.shp")
m = leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>% #http://leaflet-extras.github.io/leaflet-providers/preview/
  addScaleBar(position = c("topleft")) %>%
  addFeatures(ROI_2, group = "Fort St. John TSA", fill = FALSE)%>%
  addLayersControl(overlayGroups = c("Fort St. John TSA"), position = c("bottomleft"), options = layersControlOptions(collapsed = TRUE))
```
If so, then it will need to have a static image created as well as a new caption that will build with LaTex and web output.

**Comment by pauldpickell** [comment]
Yes, just add `m` to the last line of the net code chunk that has the `fig_cap` to call the map:

```{r 9-fort-st-john-study-area, echo=FALSE, fig.cap=fig_cap, ouwidth="75%"}
fig_cap <- paste0("The Fort St. John Timber Supply Area, British Columbia, Canada. Data from Government of British Columbia and licensed under the Open Government Licence - British Columbia. Mesler, CC-BY-SA-4.0.")
m
```

**Comment by pauldpickell** [comment]
I also would suggest renaming [this code chunk](https://github.com/ubc-geomatics-textbook/geomatics-textbook/blob/9c9f0057eaf09f31933cf63c63e0394ee51bc9aa/09-raster-analysis-terrain-modelling.Rmd#L416) from the current generic `map` to `09-fort-st-john-study-area-map` to avoid throwing warnings on output with other chunks that might also be named `map`.

**Comment by ect123** [comment]
Created the image and added the captions for each output.
