### ISSUE TITLE
Rework Index.Rmd

### ISSUE THREAD

**Issue by ect123** [ubc-geomatics-textbook/geomatics-textbook#169]
We should add some new content in the Index.Rmd in preparation for the book to be used in the classroom and elsewhere. This should replace the style guide and include:

- [x] Information about licenses
- [x] How to reuse the book
- [x] Brief introduction to the book
- [x] Contributors (financial and otherwise)

**Comment by pauldpickell** [comment]
This is completed as of #170. May revisit the acknowledgements, but I am closing this for now.
