### ISSUE TITLE
Chapter 1 citations

### ISSUE THREAD

**Issue by ect123** [ubc-geomatics-textbook/geomatics-textbook#174]
- [x] figure captions need to be converted to text references so that linked citations can be added
- [x] @pauldpickell `ch1.bib` needs to be updated so that it includes these citations:

> 1. DominionBureauStatistics_1944
> 2. Gamble_1961
> 3. Tobler_1970

**Comment by pauldpickell** [comment]
This is now solved by c8d7ef1 in #197.
