### ISSUE TITLE
Case study formatting

### ISSUE THREAD

**Issue by pauldpickell** [ubc-geomatics-textbook/geomatics-textbook#41]
The original case study css wrapper does not work well for the diversity of elements that might be contained within the wrapper. As well, text must be wrapped separately (box-text: issue #4) causing warnings when the rmd is knitted, which leads to poorly or inconsistently formatted elements. I propose we remove the case study css wrapper and instead format case studies as level 2 or level 3 headings so that they appear within the bookdown table of contents.

For example, from Chapter 2: `## Case Study: The Canadian Geodetic Vertical Datum of 2013`

The case study section name should always follow the following format: 

> Case Study: Title Case About 40 Characters Long

**Comment by pauldpickell** [comment]
To clarify, the existing case study formatting, if present, needs to be removed and replaced. It will look something like the following:

```
:::: {.box-content .case-study-content}
::: {.box-title .case-study-top}
#### Case Study {-}
:::
<p id="box-text">
You see textual case study content here
</p>
#### Another heading here
<p id="box-text">
You see textual case study content here
</p>
::::
```

The example above would be reformatted as follows:

```
## Case Study: Title of Case Study Here
You see textual case study content here

### Another Heading Here Title Case
You see textual case study content here
```

Ensure that the case study is on level 2 heading `##` and headings below the case study are organized under level 3 headings `###`. All `<p id="box-text"></p>` tags can be removed as we just want this content to be formatted like any other content in the chapter.

**Comment by ect123** [comment]
Does this close #4 ?

**Comment by pauldpickell** [comment]
No, because the other wrappers for learning objectives, your turn, and remember this still require this paragraph tag to format the text correctly.
