### ISSUE TITLE
Image sizing and properties

### ISSUE THREAD

**Issue by pauldpickell** [ubc-geomatics-textbook/geomatics-textbook#56]
Ensure that all images are either PNG or GIF. Go through all images to ensure they are not unnecessarily large in dimensions and where possible convert PNGs to 8-bit for simple diagrams with only a few colours, maintain 24-bit for true and complex images.

**Comment by ect123** [comment]
There are ~30 or so non .png / .gif images in the `/images` folder, which can be converted to .png.
