### ISSUE TITLE
Figures should be formatted with knitr

### ISSUE THREAD

**Issue by pauldpickell** [ubc-geomatics-textbook/geomatics-textbook#9]
Figures are currently formatted with `![Figure X.X Caption goes here](path/to/resource.png)`, but this does not allow for dynamic numbering of figures in the case that figures get moved around or updated in another iteration. 

Figures should be formatted like:

```{r 7-geocoding, echo=FALSE, out.width = '75%', fig.cap=fig_cap}
fig_cap <- paste("Conceptual figure showing the process of geocoding (converting addresses to geographic coordinates) and the process of reverse geocoding (converting geographic coordinates to addresses). Pickell, CC-BY-SA-4.0.")
knitr::include_graphics("images/07-geocoding.png")
```

As well, in-text references to figures need to be modified from

`Something interesting to note in Figure 7.5`

to

`Something interesting to note in Figure \@ref(fig:7-geocoding)`

https://bookdown.org/yihui/bookdown/figures.html

**Comment by ect123** [comment]
- [ X] Professional Experience student job posted for this.

**Comment by pauldpickell** [comment]
Example: 

```{r 7-geocoding, echo=FALSE, out.width = '75%', fig.cap=fig_cap}
fig_cap <- paste("Conceptual figure showing the process of geocoding (converting addresses to geographic coordinates) and the process of reverse geocoding (converting geographic coordinates to addresses). Pickell, CC-BY-SA-4.0.")
knitr::include_graphics("images/07-geocoding.png")
```
